name: Standard Ebooks toolset tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '>=3.10.12'
    - name: Install Ubuntu packages
      run: |
        sudo apt update
        sudo apt install calibre default-jre git python3-venv
    - name: Install pipx packages
      run: |
        pipx install .
        pipx inject standardebooks pylint==3.3.3 mypy==1.14.0 types-requests==2.32.0.20241016 types-setuptools==75.6.0.20241223 types-Pillow==10.2.0.20240822 pytest==8.3.4
    - name: Check type annotations with mypy
      run: $PIPX_HOME/venvs/standardebooks/bin/mypy
    - name: Check code with pylint
      run: $PIPX_HOME/venvs/standardebooks/bin/pylint tests/*.py se
    - name: Test with pytest
      run: $PIPX_HOME/venvs/standardebooks/bin/pytest
